"""remove title of the content entity

Revision ID: 0821cd9f8195
Revises: 0fef6c667dac
Create Date: 2024-05-01 18:15:59.850503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0821cd9f8195'
down_revision: Union[str, None] = '0fef6c667dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
