"""Add title to content table

Revision ID: adaf0887295d
Revises: 10d2dc75342d
Create Date: 2024-05-20 10:18:18.347624

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adaf0887295d"
down_revision: Union[str, None] = "10d2dc75342d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contents", sa.Column("title", sa.String(length=255), nullable=False), server_default="Change de title"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contents", "title")
    # ### end Alembic commands ###
